name: Build

# Controls when the workflow will run
on: 
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.*

      - name: Build the solution
        run: dotnet build Plugin.sln
             
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoReset
          path: out/Debug/
        
      - name: Prepare Artifact
        id: pa
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          Compress-Archive -Path 'out\Debug\' -DestinationPath  'Plugins_6.0.zip'

      
      - name: Release
        uses: ncipollo/release-action@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          tag: V1.0.0.0
          name: "Official Version"
          body: "每当仓库更新都会更新此Release\n此仓库只有这一个Release.\n${{steps.external_changelog_second.outputs.changelog}}"
          artifacts: Plugins_6.0.zip
          allowUpdates: true
          removeArtifacts: true
