name: NET

on:
  push:
    branches: [ "master","cai" ]
    
jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Initialize .NET 6
        uses: actions/setup-dotnet@v3
        env:
          DOTNET_CLI_UI_LANGUAGE: zh-CN
        with:
          dotnet-version: 6.0.x
          
      - name: Build Plugin
        run: |
          dotnet build Plugin.sln -c Release

      - name: Initialize Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          
      - name: Install Pypandoc
        run: 
          pip install pypandoc
        env:
          PYTHONIOENCODING: 'utf-8'
      - name: Install Requests
        run: 
          pip install requests
        env:
          PYTHONIOENCODING: 'utf-8'

      - name: Package
        run: 
          python BuildHelper.py Release
        env:
          PYTHONIOENCODING: 'utf-8'
      
      - name: Temporary Upload Plugin
        uses: actions/upload-artifact@v3
        with:
          name: Plugins
          path: Plugins.zip

      - name: Prepare Release Files
        uses: actions/upload-artifact@v3
        with:
          name: Plugins
          path: Plugins.zip
          
  LatestRelease:
    name: Latest Release
    runs-on: ubuntu-latest
    needs: Build
    permissions:
         contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Changelog
        id: external_changelog_second
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: "Config/Config_Rep.json"
            #cache: ${{ steps.external_changelog_collect.outputs.cache }}
      - name: Echo External Repo Configuration Changelog
        env:
          CHANGELOG: ${{ steps.external_changelog_second.outputs.changelog }}
          CHANGELOG_SECOND: ${{ steps.external_changelog_second.outputs.changelog }}
        run: |
          echo ${{ steps.external_changelog_collect.outputs.cache }}
          echo "First:"
          echo "$CHANGELOG"

          echo "Second:"
          echo "$CHANGELOG_SECOND"
          
      - name: Update Tag
        run: |
          git tag -f V1.0.0.0
          git push -f origin V1.0.0.0
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: Plugins
          path: ./bin
      - name: Update Latest Release
        uses: ncipollo/release-action@v1
        with:
          tag: V1.0.0.0
          name: "Latest Version"
          body: "每当仓库更新都会更新此Release\n此仓库只有这一个Release.\n${{steps.external_changelog_second.outputs.changelog}}"
          artifacts: |
            ./bin/*
          allowUpdates: true
          removeArtifacts: true
          
      
         
  ClearTempArtifacts:
    name: Clear Temp Artifacts
    if: always()
    runs-on: ubuntu-latest
    needs:
      - LatestRelease
    permissions:
      actions: write
    steps:
      - uses: geekyeggo/delete-artifact@v2
        with:
          name: |
            Plugins
