name: Fancy Release Drafter

on:
  workflow_call:

permissions:
  contents: read

jobs:
  update-release-log:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Note
        uses: release-drafter/release-drafter@v5.21.1
      - with:
           config-name: Note.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
