name: Release Drafter Workflow

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  release-drafter:
    runs-on: ubuntu-latest

    steps:
      - uses: release-drafter/release-drafter@v5.23.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
        with:
          commitish: main
          config-name: Note.yml
